# Generated by Django 5.0.8 on 2024-08-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApi', '0006_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
