# Generated by Django 5.0.8 on 2024-08-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApi', '0008_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
